/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package databasegui;


import java.awt.Image;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.ImageIcon;


/**
 *
 * @author HOU15115340
 */
public class Cars extends javax.swing.JFrame {
    private CustomerConnection dc = null; 
    private ArrayList data = null;
    /**
     * Creates new form Cars
     */
    public Cars() {
        initComponents();
         dc = new CustomerConnection();//connecting the form to the database
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPicture = new javax.swing.JLabel();
        txtCarMake = new javax.swing.JTextField();
        txtCarID = new javax.swing.JTextField();
        txtCarModel = new javax.swing.JTextField();
        txtCarColour = new javax.swing.JTextField();
        txtCarYear = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCarEngine = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtBodyType = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtMileage = new javax.swing.JTextField();
        txtTransmission = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtFuelType = new javax.swing.JTextField();
        txtCondition = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstCars = new javax.swing.JList<>();
        btnList = new javax.swing.JButton();
        btnMainMenu = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 204, 255));
        setForeground(java.awt.Color.darkGray);
        getContentPane().setLayout(null);

        lblPicture.setText("jLabel1");
        getContentPane().add(lblPicture);
        lblPicture.setBounds(55, 58, 174, 157);

        txtCarMake.setEditable(false);
        txtCarMake.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCarMakeMouseClicked(evt);
            }
        });
        getContentPane().add(txtCarMake);
        txtCarMake.setBounds(400, 90, 140, 26);

        txtCarID.setEditable(false);
        getContentPane().add(txtCarID);
        txtCarID.setBounds(400, 60, 140, 26);

        txtCarModel.setEditable(false);
        getContentPane().add(txtCarModel);
        txtCarModel.setBounds(400, 120, 140, 26);

        txtCarColour.setEditable(false);
        txtCarColour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCarColourActionPerformed(evt);
            }
        });
        getContentPane().add(txtCarColour);
        txtCarColour.setBounds(400, 150, 140, 26);

        txtCarYear.setEditable(false);
        getContentPane().add(txtCarYear);
        txtCarYear.setBounds(400, 180, 140, 26);

        jLabel2.setBackground(new java.awt.Color(102, 102, 255));
        jLabel2.setFont(new java.awt.Font("Copperplate Gothic Bold", 2, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CarID:");
        jLabel2.setToolTipText("");
        jLabel2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(310, 60, 66, 20);

        jLabel3.setBackground(new java.awt.Color(102, 102, 255));
        jLabel3.setFont(new java.awt.Font("Copperplate Gothic Bold", 2, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Make:");
        jLabel3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(320, 90, 61, 20);

        jLabel4.setBackground(new java.awt.Color(102, 102, 255));
        jLabel4.setFont(new java.awt.Font("Copperplate Gothic Bold", 2, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Colour:");
        jLabel4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(300, 150, 81, 20);

        jLabel5.setBackground(new java.awt.Color(102, 102, 255));
        jLabel5.setFont(new java.awt.Font("Copperplate Gothic Bold", 2, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Model:");
        jLabel5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(310, 120, 73, 20);

        jLabel6.setBackground(new java.awt.Color(102, 102, 255));
        jLabel6.setFont(new java.awt.Font("Copperplate Gothic Bold", 2, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Year:");
        jLabel6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(jLabel6);
        jLabel6.setBounds(330, 180, 54, 20);

        txtCarEngine.setEditable(false);
        getContentPane().add(txtCarEngine);
        txtCarEngine.setBounds(400, 210, 140, 26);

        jLabel12.setBackground(new java.awt.Color(102, 102, 255));
        jLabel12.setFont(new java.awt.Font("Copperplate Gothic Bold", 2, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Engine Size:");
        jLabel12.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(jLabel12);
        jLabel12.setBounds(260, 210, 120, 20);

        jLabel14.setFont(new java.awt.Font("Impact", 2, 36)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Cars");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(340, 20, 191, 30);

        txtBodyType.setEditable(false);
        getContentPane().add(txtBodyType);
        txtBodyType.setBounds(730, 60, 140, 26);

        jLabel15.setBackground(new java.awt.Color(102, 102, 255));
        jLabel15.setFont(new java.awt.Font("Copperplate Gothic Bold", 2, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Body Type:");
        jLabel15.setToolTipText("");
        jLabel15.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(jLabel15);
        jLabel15.setBounds(600, 60, 110, 20);

        jLabel16.setBackground(new java.awt.Color(102, 102, 255));
        jLabel16.setFont(new java.awt.Font("Copperplate Gothic Bold", 2, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Mileage:");
        jLabel16.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(jLabel16);
        jLabel16.setBounds(620, 90, 88, 20);

        txtMileage.setEditable(false);
        getContentPane().add(txtMileage);
        txtMileage.setBounds(730, 90, 140, 26);

        txtTransmission.setEditable(false);
        getContentPane().add(txtTransmission);
        txtTransmission.setBounds(730, 120, 140, 26);

        jLabel17.setBackground(new java.awt.Color(102, 102, 255));
        jLabel17.setFont(new java.awt.Font("Copperplate Gothic Bold", 2, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Transmission:");
        jLabel17.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(jLabel17);
        jLabel17.setBounds(570, 120, 135, 20);

        jLabel18.setBackground(new java.awt.Color(102, 102, 255));
        jLabel18.setFont(new java.awt.Font("Copperplate Gothic Bold", 2, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Fuel Type:");
        jLabel18.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(jLabel18);
        jLabel18.setBounds(600, 150, 105, 20);

        txtFuelType.setEditable(false);
        getContentPane().add(txtFuelType);
        txtFuelType.setBounds(730, 150, 140, 26);

        txtCondition.setEditable(false);
        getContentPane().add(txtCondition);
        txtCondition.setBounds(730, 180, 140, 26);

        jLabel19.setBackground(new java.awt.Color(102, 102, 255));
        jLabel19.setFont(new java.awt.Font("Copperplate Gothic Bold", 2, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Condition:");
        jLabel19.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(jLabel19);
        jLabel19.setBounds(610, 180, 104, 20);

        jLabel20.setBackground(new java.awt.Color(102, 102, 255));
        jLabel20.setFont(new java.awt.Font("Copperplate Gothic Bold", 2, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Price:");
        jLabel20.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(jLabel20);
        jLabel20.setBounds(650, 210, 61, 20);

        txtPrice.setEditable(false);
        getContentPane().add(txtPrice);
        txtPrice.setBounds(730, 210, 140, 26);

        lstCars.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstCarsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lstCars);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 250, 820, 120);

        btnList.setFont(new java.awt.Font("Copperplate Gothic Bold", 2, 18)); // NOI18N
        btnList.setText("BROWSE ALL CARS");
        btnList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListActionPerformed(evt);
            }
        });
        getContentPane().add(btnList);
        btnList.setBounds(320, 380, 237, 29);

        btnMainMenu.setFont(new java.awt.Font("Copperplate Gothic Bold", 2, 18)); // NOI18N
        btnMainMenu.setText("Back to the Main Menu");
        btnMainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMainMenuActionPerformed(evt);
            }
        });
        getContentPane().add(btnMainMenu);
        btnMainMenu.setBounds(30, 380, 267, 29);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgimages/car seat.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 880, 420);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListActionPerformed
        //adding all of the cars from the database into the list box 
        lstCars.removeAll();
        data = dc.getAllCars();
        Vector listData = new Vector(); 
        for(int index=0;index<data.size();index++){
            CarsClass temp = (CarsClass)data.get(index);
            listData.addElement(temp.getCarID()+"  "+temp.getMake()+"  "+temp.getModel()+"  "+temp.getColour()+"  "+temp.getYear()+"  "+temp.getEngineSize()+"  "+temp.getBodyType()+"  "+temp.getMileage()+"  "+temp.getTransmission()+"  "+temp.getFuelType()+"  "+temp.getCondition()+"  "+temp.getPrice());
        }
        lstCars.setListData(listData);
    }//GEN-LAST:event_btnListActionPerformed

    private void txtCarMakeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCarMakeMouseClicked
     
    }//GEN-LAST:event_txtCarMakeMouseClicked
    
    private void lstCarsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstCarsMouseClicked
        // TODO add your handling code herint index = lstCars.getSelectedIndex();
        //when selecting a car from the list box, this method allows for the information
        //to be copied into the above fields along with the picture of the car
        int index = lstCars.getSelectedIndex();
        if (data != null && index != -1){
            CarsClass temp = (CarsClass)data.get(index);
            txtCarID.setText(temp.getCarID());
            txtCarMake.setText(temp.getMake());
            txtCarModel.setText(temp.getModel());
            txtCarColour.setText(temp.getColour());
            txtCarYear.setText(temp.getYear());
            txtCarEngine.setText(temp.getEngineSize());
            txtBodyType.setText(temp.getBodyType());
            txtMileage.setText(temp.getMileage());
            txtTransmission.setText(temp.getTransmission());
            txtFuelType.setText(temp.getFuelType());
            txtCondition.setText(temp.getCondition());
            txtPrice.setText(temp.getPrice());   
            Image pic = temp.getImage();
            int w = lblPicture.getWidth();
            int h = lblPicture.getHeight();
            pic = pic.getScaledInstance(w,h,1);
            lblPicture.setIcon(new ImageIcon(pic));
            
    }//GEN-LAST:event_lstCarsMouseClicked
    }
    private void txtCarColourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCarColourActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCarColourActionPerformed

    private void btnMainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMainMenuActionPerformed
        //returns the user to the main menu
        MainMenu form1 = new MainMenu();
        form1.setVisible( true );
        this.setVisible(false);
    }//GEN-LAST:event_btnMainMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cars.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cars.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cars.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cars.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cars().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnList;
    private javax.swing.JButton btnMainMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPicture;
    private javax.swing.JList<String> lstCars;
    private javax.swing.JTextField txtBodyType;
    private javax.swing.JTextField txtCarColour;
    private javax.swing.JTextField txtCarEngine;
    private javax.swing.JTextField txtCarID;
    private javax.swing.JTextField txtCarMake;
    private javax.swing.JTextField txtCarModel;
    private javax.swing.JTextField txtCarYear;
    private javax.swing.JTextField txtCondition;
    private javax.swing.JTextField txtFuelType;
    private javax.swing.JTextField txtMileage;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtTransmission;
    // End of variables declaration//GEN-END:variables

}