/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package databasegui;

import javax.swing.JOptionPane;

/**
 *
 * @author MAR18146923
 */
public class CustomerGUI extends javax.swing.JFrame {

    private CustomerConnection CustomerConnection;
    private Customer[] arrayOfCustomers;
    private int currentIndex;
    private int numberOfRecords;

    /**
     * Creates new form CustomerGUI
     */
    public CustomerGUI() {
        initComponents();
        CustomerConnection = new CustomerConnection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPrevious = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        lblCustomerID = new javax.swing.JLabel();
        lblFirstname = new javax.swing.JLabel();
        lblSurname = new javax.swing.JLabel();
        lblStreet = new javax.swing.JLabel();
        lblTown = new javax.swing.JLabel();
        lblCity = new javax.swing.JLabel();
        lblPostcode = new javax.swing.JLabel();
        lblContactNumber = new javax.swing.JLabel();
        browseButton = new javax.swing.JButton();
        customerIDTextField = new javax.swing.JTextField();
        firstnameTextField = new javax.swing.JTextField();
        surnameTextField = new javax.swing.JTextField();
        streetTextField = new javax.swing.JTextField();
        townTextField = new javax.swing.JTextField();
        cityTextField = new javax.swing.JTextField();
        postcodeTextField = new javax.swing.JTextField();
        contactNumberTextField = new javax.swing.JTextField();
        currRecordTextField = new javax.swing.JTextField();
        maxRecordTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        queryButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        btnPrevious.setFont(new java.awt.Font("Copperplate Gothic Bold", 2, 18)); // NOI18N
        btnPrevious.setText("Previous");
        btnPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousActionPerformed(evt);
            }
        });
        getContentPane().add(btnPrevious);
        btnPrevious.setBounds(588, 449, 123, 29);
        btnPrevious.getAccessibleContext().setAccessibleName("btnPrevious");

        btnNext.setFont(new java.awt.Font("Copperplate Gothic Bold", 2, 18)); // NOI18N
        btnNext.setText("Next");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        getContentPane().add(btnNext);
        btnNext.setBounds(731, 449, 81, 29);

        lblCustomerID.setFont(new java.awt.Font("Copperplate Gothic Bold", 2, 18)); // NOI18N
        lblCustomerID.setForeground(new java.awt.Color(255, 255, 255));
        lblCustomerID.setText("Customer ID:");
        getContentPane().add(lblCustomerID);
        lblCustomerID.setBounds(48, 136, 130, 21);

        lblFirstname.setFont(new java.awt.Font("Copperplate Gothic Bold", 2, 18)); // NOI18N
        lblFirstname.setForeground(new java.awt.Color(255, 255, 255));
        lblFirstname.setText("Firstname:");
        getContentPane().add(lblFirstname);
        lblFirstname.setBounds(72, 164, 106, 21);

        lblSurname.setFont(new java.awt.Font("Copperplate Gothic Bold", 2, 18)); // NOI18N
        lblSurname.setForeground(new java.awt.Color(255, 255, 255));
        lblSurname.setText("Surname:");
        getContentPane().add(lblSurname);
        lblSurname.setBounds(85, 192, 93, 21);

        lblStreet.setFont(new java.awt.Font("Copperplate Gothic Bold", 2, 18)); // NOI18N
        lblStreet.setForeground(new java.awt.Color(255, 255, 255));
        lblStreet.setText("Street:");
        getContentPane().add(lblStreet);
        lblStreet.setBounds(103, 220, 75, 21);

        lblTown.setFont(new java.awt.Font("Copperplate Gothic Bold", 2, 18)); // NOI18N
        lblTown.setForeground(new java.awt.Color(255, 255, 255));
        lblTown.setText("Town:");
        getContentPane().add(lblTown);
        lblTown.setBounds(515, 137, 63, 21);

        lblCity.setFont(new java.awt.Font("Copperplate Gothic Bold", 2, 18)); // NOI18N
        lblCity.setForeground(new java.awt.Color(255, 255, 255));
        lblCity.setText("City:");
        getContentPane().add(lblCity);
        lblCity.setBounds(532, 165, 46, 21);

        lblPostcode.setFont(new java.awt.Font("Copperplate Gothic Bold", 2, 18)); // NOI18N
        lblPostcode.setForeground(new java.awt.Color(255, 255, 255));
        lblPostcode.setText("Postcode:");
        getContentPane().add(lblPostcode);
        lblPostcode.setBounds(473, 193, 105, 21);

        lblContactNumber.setFont(new java.awt.Font("Copperplate Gothic Bold", 2, 18)); // NOI18N
        lblContactNumber.setForeground(new java.awt.Color(255, 255, 255));
        lblContactNumber.setText("Contact Number:");
        getContentPane().add(lblContactNumber);
        lblContactNumber.setBounds(404, 220, 174, 21);

        browseButton.setFont(new java.awt.Font("Copperplate Gothic Bold", 2, 18)); // NOI18N
        browseButton.setText("Browse All Customers");
        browseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseButtonActionPerformed(evt);
            }
        });
        getContentPane().add(browseButton);
        browseButton.setBounds(10, 443, 269, 40);
        browseButton.getAccessibleContext().setAccessibleName("browseButton");

        customerIDTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerIDTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(customerIDTextField);
        customerIDTextField.setBounds(196, 138, 180, 26);
        getContentPane().add(firstnameTextField);
        firstnameTextField.setBounds(196, 166, 180, 26);
        getContentPane().add(surnameTextField);
        surnameTextField.setBounds(196, 194, 180, 26);
        getContentPane().add(streetTextField);
        streetTextField.setBounds(196, 222, 180, 26);

        townTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                townTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(townTextField);
        townTextField.setBounds(632, 138, 180, 26);
        getContentPane().add(cityTextField);
        cityTextField.setBounds(632, 167, 180, 26);
        getContentPane().add(postcodeTextField);
        postcodeTextField.setBounds(632, 193, 180, 26);
        getContentPane().add(contactNumberTextField);
        contactNumberTextField.setBounds(632, 222, 180, 26);
        getContentPane().add(currRecordTextField);
        currRecordTextField.setBounds(385, 455, 43, 26);
        getContentPane().add(maxRecordTextField);
        maxRecordTextField.setBounds(489, 455, 39, 26);

        jLabel1.setFont(new java.awt.Font("Copperplate Gothic Bold", 2, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("of");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(446, 453, 33, 21);
        getContentPane().add(txtSearch);
        txtSearch.setBounds(287, 324, 291, 26);

        queryButton.setFont(new java.awt.Font("Copperplate Gothic Bold", 2, 18)); // NOI18N
        queryButton.setText("Search Customer");
        queryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                queryButtonActionPerformed(evt);
            }
        });
        getContentPane().add(queryButton);
        queryButton.setBounds(330, 360, 211, 29);

        addButton.setFont(new java.awt.Font("Copperplate Gothic Bold", 2, 18)); // NOI18N
        addButton.setText("Add New Customer");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        getContentPane().add(addButton);
        addButton.setBounds(10, 400, 229, 37);

        btnExit.setFont(new java.awt.Font("Copperplate Gothic Bold", 2, 18)); // NOI18N
        btnExit.setText("Back to main menu");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit);
        btnExit.setBounds(597, 414, 215, 29);

        jLabel2.setFont(new java.awt.Font("Impact", 2, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CUSTOMERS");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(340, 40, 188, 45);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgimages/car seat.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 830, 520);

        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(240, 330, 51, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void browseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseButtonActionPerformed
        try {
            //set up array to store the data sent back from the StudentConnection             
            arrayOfCustomers = CustomerConnection.getAllCustomers();
            //number of items in the array             
            numberOfRecords = CustomerConnection.numRecordsInQuery;
            currentIndex = 0;
            if (numberOfRecords != 0) {
                //display the first students details                 
                String idText = Integer.toString(arrayOfCustomers[currentIndex].getcustomerID());

                customerIDTextField.setText(idText);

                firstnameTextField.setText(arrayOfCustomers[currentIndex].getFirstname());
                surnameTextField.setText(arrayOfCustomers[currentIndex].getSurname());
                streetTextField.setText(arrayOfCustomers[currentIndex].getStreet());
                townTextField.setText(arrayOfCustomers[currentIndex].getTown());
                cityTextField.setText(arrayOfCustomers[currentIndex].getCity());
                postcodeTextField.setText(arrayOfCustomers[currentIndex].getPostcode());
                contactNumberTextField.setText(arrayOfCustomers[currentIndex].getContactNumber());

                //display the current index for current and last record                 
                currRecordTextField.setText(Integer.toString(currentIndex + 1));
                maxRecordTextField.setText(Integer.toString(numberOfRecords));
                //enable buttons to navigate through students                 
                btnPrevious.setEnabled(true);
                btnNext.setEnabled(true);

            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }


                                                          }//GEN-LAST:event_browseButtonActionPerformed

    private void customerIDTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerIDTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customerIDTextFieldActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        numberOfRecords = CustomerConnection.numRecordsInQuery;
        //button will move to the record after current one         
        //if the last record is showing there will be no response         
        if (currentIndex < numberOfRecords - 1) {
            currentIndex++;
            currRecordTextField.setText(Integer.toString(currentIndex + 1));
            //display the students details at currentIndex             
            String idText = Integer.toString(arrayOfCustomers[currentIndex].getcustomerID());
            customerIDTextField.setText(idText);
            firstnameTextField.setText(arrayOfCustomers[currentIndex].getFirstname());
            surnameTextField.setText(arrayOfCustomers[currentIndex].getSurname());
            streetTextField.setText(arrayOfCustomers[currentIndex].getStreet());
            townTextField.setText(arrayOfCustomers[currentIndex].getTown());
            cityTextField.setText(arrayOfCustomers[currentIndex].getCity());
            postcodeTextField.setText(arrayOfCustomers[currentIndex].getPostcode());
            contactNumberTextField.setText(arrayOfCustomers[currentIndex].getContactNumber());

        }         // TODO add your handling code here:
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousActionPerformed
        if (currentIndex != 0) {
            currentIndex--;
            currRecordTextField.setText(Integer.toString(currentIndex + 1));
            //display the students details at currentIndex             
            String idText = Integer.toString(arrayOfCustomers[currentIndex].getcustomerID());
            customerIDTextField.setText(idText);
            firstnameTextField.setText(arrayOfCustomers[currentIndex].getFirstname());
            surnameTextField.setText(arrayOfCustomers[currentIndex].getSurname());
            streetTextField.setText(arrayOfCustomers[currentIndex].getStreet());
            townTextField.setText(arrayOfCustomers[currentIndex].getTown());
            cityTextField.setText(arrayOfCustomers[currentIndex].getCity());
            postcodeTextField.setText(arrayOfCustomers[currentIndex].getPostcode());
            contactNumberTextField.setText(arrayOfCustomers[currentIndex].getStreet());

        }
    }//GEN-LAST:event_btnPreviousActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        boolean done = CustomerConnection.addCustomer(firstnameTextField.getText(), surnameTextField.getText(), streetTextField.getText(), townTextField.getText(), cityTextField.getText(), postcodeTextField.getText(), contactNumberTextField.getText());
        if (done) {
            JOptionPane.showMessageDialog(this, "Customer added", "Adding Record", JOptionPane.PLAIN_MESSAGE);
            //reload the records by calling the browseButtonActionPerformed method with the event  
            browseButtonActionPerformed(evt);
        } else {
            JOptionPane.showMessageDialog(this, "Customer not added", "Error", JOptionPane.PLAIN_MESSAGE);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_addButtonActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        MainMenu form1 = new MainMenu();
        form1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnExitActionPerformed

    private void townTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_townTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_townTextFieldActionPerformed

    private void queryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_queryButtonActionPerformed
        String name = txtSearch.getText();
        //query database for students with LastName = name         
        arrayOfCustomers = CustomerConnection.getCustomersByName(name);
        numberOfRecords = CustomerConnection.numRecordsInQuery;
        //if there were any matches  
        currentIndex = 0;
        if (numberOfRecords != 0) {
            //display the first students details             
            String idText = Integer.toString(arrayOfCustomers[currentIndex].getcustomerID());
            customerIDTextField.setText(idText);
            firstnameTextField.setText(arrayOfCustomers[currentIndex].getFirstname());
            surnameTextField.setText(arrayOfCustomers[currentIndex].getSurname());
            streetTextField.setText(arrayOfCustomers[currentIndex].getStreet());
            townTextField.setText(arrayOfCustomers[currentIndex].getTown());
            cityTextField.setText(arrayOfCustomers[currentIndex].getCity());
            postcodeTextField.setText(arrayOfCustomers[currentIndex].getPostcode());

            //display the current index for current and last record             
            currRecordTextField.setText(Integer.toString(currentIndex + 1));
            maxRecordTextField.setText(Integer.toString(numberOfRecords));
        } else {
            JOptionPane.showMessageDialog(this, "No Records found", "Query Result", JOptionPane.PLAIN_MESSAGE);
        }             // TODO add your handling code here:
    }//GEN-LAST:event_queryButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerGUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerGUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerGUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerGUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton browseButton;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrevious;
    private javax.swing.JTextField cityTextField;
    private javax.swing.JTextField contactNumberTextField;
    private javax.swing.JTextField currRecordTextField;
    private javax.swing.JTextField customerIDTextField;
    private javax.swing.JTextField firstnameTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblContactNumber;
    private javax.swing.JLabel lblCustomerID;
    private javax.swing.JLabel lblFirstname;
    private javax.swing.JLabel lblPostcode;
    private javax.swing.JLabel lblStreet;
    private javax.swing.JLabel lblSurname;
    private javax.swing.JLabel lblTown;
    private javax.swing.JTextField maxRecordTextField;
    private javax.swing.JTextField postcodeTextField;
    private javax.swing.JButton queryButton;
    private javax.swing.JTextField streetTextField;
    private javax.swing.JTextField surnameTextField;
    private javax.swing.JTextField townTextField;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
