/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package databasegui;

import java.awt.Image;
import java.util.ArrayList;
import java.util.Vector;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author b-hou
 */
public class Order extends javax.swing.JFrame {
   // private CustomerConnection CustomerConnection;
    private CustomerConnection dc = null;
    private ArrayList data = null;
   // private Order[] Order;
    //private int currentIndex;

    /**
     * Creates new form Order
     */
    public Order() {
        initComponents();
        dc = new CustomerConnection();
        //CustomerConnection = new CustomerConnection();

        updateLists();
        updateList();

    }

    private void updateLists() {
        cboStaff.removeAll();
        data = dc.getAllOrders();
        Vector ComboData = new Vector();
        for (int index = 0; index < data.size(); index++) {
            OrdersClass temp = (OrdersClass) data.get(index);
            ComboData.addElement(temp.getForename() + " " + temp.getLastname());

        }

    }

    private void updateList() {
        // update combo and listbox
        cboCustomers.removeAll();
        data = dc.getAllOrders();
        Vector ComboData = new Vector();
        for (int index = 0; index < data.size(); index++) {
            OrdersClass temp = (OrdersClass) data.get(index);
            ComboData.addElement(temp.getFirstname() + " "
                    + temp.getsurname() + "" + temp.getStreet() + " " + temp.getTown() + " "
                    + temp.getCity() + " " + temp.getPostcode() + " " + temp.getContactNumber());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cboCustomers = new javax.swing.JComboBox<>();
        cboStaff = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtStreet = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtSurname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTown = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtCity = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtPost = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtContact = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtStaffF = new javax.swing.JTextField();
        txtStaffS = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        browseOrders = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        txtCarID = new javax.swing.JTextField();
        txtCarMake = new javax.swing.JTextField();
        txtCarModel = new javax.swing.JTextField();
        txtCarColour = new javax.swing.JTextField();
        txtCarYear = new javax.swing.JTextField();
        txtCarEngine = new javax.swing.JTextField();
        txtBodyType = new javax.swing.JTextField();
        txtMileage = new javax.swing.JTextField();
        txtTransmission = new javax.swing.JTextField();
        txtFuelType = new javax.swing.JTextField();
        txtCondition = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnPurchase = new javax.swing.JButton();
        btnMainMenu = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        txtPaymentDate = new javax.swing.JTextField();
        lblPicture = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtCustomerID = new javax.swing.JTextField();
        txtStaffID = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        cboCustomers.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CustomerID 1", "CustomerID 2", "CustomerID 3 ", "CustomerID 4", " " }));
        cboCustomers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboCustomersActionPerformed(evt);
            }
        });
        getContentPane().add(cboCustomers);
        cboCustomers.setBounds(200, 100, 240, 36);

        cboStaff.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "StaffID 1", "StaffID 2", "StaffID 3", "StaffID 4" }));
        cboStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboStaffActionPerformed(evt);
            }
        });
        getContentPane().add(cboStaff);
        cboStaff.setBounds(590, 100, 240, 36);

        jLabel1.setFont(new java.awt.Font("Copperplate Gothic Bold", 2, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Firstname:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(80, 160, 106, 21);
        getContentPane().add(txtName);
        txtName.setBounds(200, 160, 236, 20);

        jLabel2.setFont(new java.awt.Font("Copperplate Gothic Bold", 2, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Surname:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(80, 190, 106, 21);
        getContentPane().add(txtStreet);
        txtStreet.setBounds(200, 220, 236, 20);

        jLabel3.setFont(new java.awt.Font("Copperplate Gothic Bold", 2, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Street:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(100, 220, 91, 21);
        getContentPane().add(txtSurname);
        txtSurname.setBounds(200, 190, 236, 20);

        jLabel4.setFont(new java.awt.Font("Copperplate Gothic Bold", 2, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Town:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(100, 250, 91, 21);
        getContentPane().add(txtTown);
        txtTown.setBounds(200, 250, 236, 20);

        jLabel5.setFont(new java.awt.Font("Copperplate Gothic Bold", 2, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("City:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(90, 280, 91, 21);
        getContentPane().add(txtCity);
        txtCity.setBounds(200, 280, 236, 20);

        jLabel6.setFont(new java.awt.Font("Copperplate Gothic Bold", 2, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Postcode:");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(jLabel6);
        jLabel6.setBounds(60, 310, 130, 21);
        getContentPane().add(txtPost);
        txtPost.setBounds(200, 310, 236, 20);

        jLabel7.setFont(new java.awt.Font("Copperplate Gothic Bold", 2, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Contatc Number:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 340, 174, 21);
        getContentPane().add(txtContact);
        txtContact.setBounds(200, 340, 236, 20);

        jLabel8.setFont(new java.awt.Font("Copperplate Gothic Bold", 2, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Firstname:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(470, 160, 106, 21);
        getContentPane().add(txtStaffF);
        txtStaffF.setBounds(590, 160, 236, 20);
        getContentPane().add(txtStaffS);
        txtStaffS.setBounds(590, 190, 236, 20);

        jLabel9.setFont(new java.awt.Font("Copperplate Gothic Bold", 2, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Surname:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(470, 190, 106, 21);

        browseOrders.setFont(new java.awt.Font("Copperplate Gothic Bold", 2, 18)); // NOI18N
        browseOrders.setText("Browse Cars");
        browseOrders.setToolTipText("");
        browseOrders.setDefaultCapable(false);
        browseOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseOrdersActionPerformed(evt);
            }
        });
        getContentPane().add(browseOrders);
        browseOrders.setBounds(420, 640, 213, 37);

        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(420, 450, 610, 130);
        getContentPane().add(txtCarID);
        txtCarID.setBounds(590, 260, 150, 20);
        getContentPane().add(txtCarMake);
        txtCarMake.setBounds(590, 290, 150, 20);

        txtCarModel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCarModelActionPerformed(evt);
            }
        });
        getContentPane().add(txtCarModel);
        txtCarModel.setBounds(590, 320, 150, 20);
        getContentPane().add(txtCarColour);
        txtCarColour.setBounds(590, 380, 150, 20);
        getContentPane().add(txtCarYear);
        txtCarYear.setBounds(590, 350, 150, 20);

        txtCarEngine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCarEngineActionPerformed(evt);
            }
        });
        getContentPane().add(txtCarEngine);
        txtCarEngine.setBounds(590, 410, 150, 20);
        getContentPane().add(txtBodyType);
        txtBodyType.setBounds(900, 260, 110, 20);
        getContentPane().add(txtMileage);
        txtMileage.setBounds(900, 290, 110, 20);
        getContentPane().add(txtTransmission);
        txtTransmission.setBounds(900, 320, 110, 20);

        txtFuelType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFuelTypeActionPerformed(evt);
            }
        });
        getContentPane().add(txtFuelType);
        txtFuelType.setBounds(900, 350, 110, 20);
        getContentPane().add(txtCondition);
        txtCondition.setBounds(900, 380, 110, 20);
        getContentPane().add(txtPrice);
        txtPrice.setBounds(900, 410, 110, 20);

        jLabel11.setFont(new java.awt.Font("Copperplate Gothic Bold", 2, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("CarID:");
        jLabel11.setToolTipText("");
        jLabel11.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(jLabel11);
        jLabel11.setBounds(510, 260, 70, 20);

        jLabel12.setFont(new java.awt.Font("Copperplate Gothic Bold", 2, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Make:");
        jLabel12.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(jLabel12);
        jLabel12.setBounds(520, 290, 70, 20);

        jLabel13.setFont(new java.awt.Font("Copperplate Gothic Bold", 2, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Model:");
        jLabel13.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(jLabel13);
        jLabel13.setBounds(510, 320, 80, 20);

        jLabel14.setFont(new java.awt.Font("Copperplate Gothic Bold", 2, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Colour:");
        jLabel14.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(jLabel14);
        jLabel14.setBounds(500, 380, 90, 20);

        jLabel15.setFont(new java.awt.Font("Copperplate Gothic Bold", 2, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Year:");
        jLabel15.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(jLabel15);
        jLabel15.setBounds(530, 350, 60, 20);

        jLabel16.setFont(new java.awt.Font("Copperplate Gothic Bold", 2, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Engine Size:");
        jLabel16.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(jLabel16);
        jLabel16.setBounds(460, 410, 120, 20);

        jLabel17.setFont(new java.awt.Font("Copperplate Gothic Bold", 2, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Body Type:");
        jLabel17.setToolTipText("");
        jLabel17.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(jLabel17);
        jLabel17.setBounds(780, 260, 110, 20);

        jLabel18.setFont(new java.awt.Font("Copperplate Gothic Bold", 2, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Mileage:");
        jLabel18.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(jLabel18);
        jLabel18.setBounds(798, 290, 100, 20);

        jLabel19.setFont(new java.awt.Font("Copperplate Gothic Bold", 2, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Transmission:");
        jLabel19.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(jLabel19);
        jLabel19.setBounds(755, 320, 140, 20);

        jLabel20.setFont(new java.awt.Font("Copperplate Gothic Bold", 2, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Fuel Type:");
        jLabel20.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(jLabel20);
        jLabel20.setBounds(785, 350, 110, 20);

        jLabel21.setFont(new java.awt.Font("Copperplate Gothic Bold", 2, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Condition:");
        jLabel21.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(jLabel21);
        jLabel21.setBounds(784, 380, 110, 20);

        jLabel22.setFont(new java.awt.Font("Copperplate Gothic Bold", 2, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Price:");
        jLabel22.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(jLabel22);
        jLabel22.setBounds(821, 410, 70, 20);

        jLabel10.setFont(new java.awt.Font("Impact", 2, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("ORDER FORM");
        jLabel10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel10);
        jLabel10.setBounds(440, 20, 200, 40);

        btnPurchase.setFont(new java.awt.Font("Copperplate Gothic Bold", 2, 18)); // NOI18N
        btnPurchase.setText("Purchase");
        btnPurchase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPurchaseActionPerformed(evt);
            }
        });
        getContentPane().add(btnPurchase);
        btnPurchase.setBounds(860, 639, 170, 40);

        btnMainMenu.setFont(new java.awt.Font("Copperplate Gothic Bold", 2, 18)); // NOI18N
        btnMainMenu.setText("Back to main menu");
        btnMainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMainMenuActionPerformed(evt);
            }
        });
        getContentPane().add(btnMainMenu);
        btnMainMenu.setBounds(30, 640, 230, 40);

        jLabel24.setFont(new java.awt.Font("Copperplate Gothic Bold", 2, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Quantity:");
        jLabel24.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(jLabel24);
        jLabel24.setBounds(750, 590, 120, 30);
        getContentPane().add(txtQuantity);
        txtQuantity.setBounds(860, 590, 130, 20);

        jLabel25.setFont(new java.awt.Font("Copperplate Gothic Bold", 2, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Payment Date:");
        getContentPane().add(jLabel25);
        jLabel25.setBounds(730, 20, 160, 21);
        getContentPane().add(txtPaymentDate);
        txtPaymentDate.setBounds(884, 20, 140, 20);

        lblPicture.setText("jLabel26");
        getContentPane().add(lblPicture);
        lblPicture.setBounds(50, 410, 270, 200);

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgimages/car seat.jpg"))); // NOI18N
        jLabel23.setText("jLabel23");
        getContentPane().add(jLabel23);
        jLabel23.setBounds(0, 0, 1040, 710);

        txtCustomerID.setText("jTextField1");
        getContentPane().add(txtCustomerID);
        txtCustomerID.setBounds(1060, 70, 59, 20);

        txtStaffID.setText("jTextField2");
        getContentPane().add(txtStaffID);
        txtStaffID.setBounds(1070, 100, 59, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboCustomersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboCustomersActionPerformed
     
        int index = cboCustomers.getSelectedIndex();
        if (data != null && index != -1) {
            OrdersClass temp = (OrdersClass) data.get(index);
            txtCustomerID.setText(temp.getcustomerID());
            txtName.setText(temp.getFirstname());
            txtSurname.setText(temp.getsurname());
            txtStreet.setText(temp.getStreet());
            txtTown.setText(temp.getTown());
            txtCity.setText(temp.getCity());
            txtPost.setText(temp.getPostcode());
            txtContact.setText(temp.getContactNumber());
        }
    }//GEN-LAST:event_cboCustomersActionPerformed

    private void browseOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseOrdersActionPerformed
        jList1.removeAll();
        data = dc.getAllOrders();
        Vector listData = new Vector();
        for (int index = 0; index < data.size(); index++) {
            OrdersClass temp = (OrdersClass) data.get(index);
            listData.addElement(temp.getCarID() + "  " + temp.getMake() + "  "
                    + temp.getModel() + "  " + temp.getColour() + "  " + temp.getYear()
                    + "  " + temp.getEngineSize() + "  " + temp.getBodyType() + "  "
                    + temp.getMileage() + "  " + temp.getTransmission() + "  "
                    + temp.getFuelType() + "  " + temp.getCondition() + "  " + temp.getPrice());
        }
        jList1.setListData(listData);

    }//GEN-LAST:event_browseOrdersActionPerformed

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
  
        int index = jList1.getSelectedIndex();
        if (data != null && index != -1) {
            OrdersClass temp = (OrdersClass) data.get(index);
            txtCarID.setText(temp.getCarID());
            txtCarMake.setText(temp.getMake());
            txtCarModel.setText(temp.getModel());
            txtCarColour.setText(temp.getColour());
            txtCarYear.setText(temp.getYear());
            txtCarEngine.setText(temp.getEngineSize());
            txtBodyType.setText(temp.getBodyType());
            txtMileage.setText(temp.getMileage());
            txtTransmission.setText(temp.getTransmission());
            txtFuelType.setText(temp.getFuelType());
            txtCondition.setText(temp.getCondition());
            txtPrice.setText(temp.getPrice());
            Image pic = temp.getImage();
            int w = lblPicture.getWidth();
            int h = lblPicture.getHeight();
            pic = pic.getScaledInstance(w,h,1);
            lblPicture.setIcon(new ImageIcon(pic));
        }
    }//GEN-LAST:event_jList1MouseClicked

    private void txtFuelTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFuelTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFuelTypeActionPerformed

    private void cboStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboStaffActionPerformed
        int index = cboStaff.getSelectedIndex();
        if (data != null && index != -1) {
            OrdersClass temp = (OrdersClass) data.get(index);
            txtStaffID.setText(temp.getStaffID());
            txtStaffF.setText(temp.getForename());
            txtStaffS.setText(temp.getLastname());
        }

    }//GEN-LAST:event_cboStaffActionPerformed

    private void txtCarModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCarModelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCarModelActionPerformed

    private void txtCarEngineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCarEngineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCarEngineActionPerformed

    private void btnMainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMainMenuActionPerformed
        MainMenu form1 = new MainMenu();
        form1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnMainMenuActionPerformed

    private void btnPurchaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPurchaseActionPerformed
        //boolean done = CustomerConnection.addOrder(txtQuantity.getText(), txtPaymentDate.getText(), txtCarID.getText(), txtStaffID.getText(), txtCustomerID.getText());
      //  if (done) {
            JOptionPane.showMessageDialog(this, "Purchased Confirmed", "Adding Record", JOptionPane.PLAIN_MESSAGE);
            //reload the records by calling the browseButtonActionPerformed method with the event  
      
       // } else {
           // JOptionPane.showMessageDialog(this, "Customer not added", "Error", JOptionPane.PLAIN_MESSAGE);
        //}        // TODO add your handling code here:
    }//GEN-LAST:event_btnPurchaseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Order().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton browseOrders;
    private javax.swing.JButton btnMainMenu;
    private javax.swing.JButton btnPurchase;
    private javax.swing.JComboBox<String> cboCustomers;
    private javax.swing.JComboBox<String> cboStaff;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPicture;
    private javax.swing.JTextField txtBodyType;
    private javax.swing.JTextField txtCarColour;
    private javax.swing.JTextField txtCarEngine;
    private javax.swing.JTextField txtCarID;
    private javax.swing.JTextField txtCarMake;
    private javax.swing.JTextField txtCarModel;
    private javax.swing.JTextField txtCarYear;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtCondition;
    private javax.swing.JTextField txtContact;
    private javax.swing.JTextField txtCustomerID;
    private javax.swing.JTextField txtFuelType;
    private javax.swing.JTextField txtMileage;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPaymentDate;
    private javax.swing.JTextField txtPost;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtStaffF;
    private javax.swing.JTextField txtStaffID;
    private javax.swing.JTextField txtStaffS;
    private javax.swing.JTextField txtStreet;
    private javax.swing.JTextField txtSurname;
    private javax.swing.JTextField txtTown;
    private javax.swing.JTextField txtTransmission;
    // End of variables declaration//GEN-END:variables
}
